# Generated by Django 5.1.7 on 2025-03-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsarticle_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='category',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.ManyToManyField(default=None, related_name='articles', to='news.category'),
        ),
    ]
