# Generated by Django 5.1.7 on 2025-03-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newsarticle_category_newsarticle_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='category',
            new_name='categories',
        ),
    ]
